- [Gear, gear, data-icon: fa-gear]
- [Globe, globe, data-icon: fa-globe]
- [Adjust, adjust, data-icon: fa-adjust]
- [Camera, camera, data-icon: fa-camera]
- [Glass, glass, data-icon: fa-martini-glass]
- [Music, music, data-icon: fa-music]
- [Heart, heart, data-icon: fa-heart]
- [Star, star, data-icon: fa-star]
- [Film, film, data-icon: fa-film]
- [Signal, signal, data-icon: fa-signal]
- [Home, home, data-icon: fa-home]
- [Automobile, automobile, data-icon: fa-automobile]
- [Clock, clock-o, data-icon: fa-clock]
- [Road, road, data-icon: fa-road]
- [Inbox, inbox, data-icon: fa-inbox]
- [Lock, lock, data-icon: fa-lock]
- [Flag, flag, data-icon: fa-flag]
- [Spoon, spoon, data-icon: fa-spoon]
- [Barcode, barcode, data-icon: fa-barcode]
- [Book, book, data-icon: fa-book]
- [Building, building, data-icon: fa-building]
- [Video Camera, video-camera, data-icon: fa-video-camera]
- [Photo, photo, data-icon: fa-image]
- [Headphones, headphones, data-icon: fa-headphones]
- [Gift, gift, data-icon: fa-gift]
- [Leaf, leaf, data-icon: fa-leaf]
- [Fire, fire, data-icon: fa-fire]
- [Eye, eye, data-icon: fa-eye]
- [Language, language, data-icon: fa-language]
- [Key, key, data-icon: fa-key]
- [Paw, paw, data-icon: fa-paw]
- [Tags, tags, data-icon: fa-tags]
- [Dashboard, dashboard, data-icon: fa-dashboard]
- [Camera Retro, camera-retro, data-icon: fa-camera-retro]
- [Plane, plane, data-icon: fa-plane]
- [Calendar, calendar, data-icon: fa-calendar]
- [Bullhorn, bullhorn, data-icon: fa-bullhorn]
- [Gears, gears, data-icon: fa-gears]
- [Bell, bell, data-icon: fa-bell]
- [Gavel, gavel, data-icon: fa-gavel]
- [Tachometer, tachometer, data-icon: fa-tachometer]
- [Bank, bank, data-icon: fa-bank]
- [Coffee, coffee, data-icon: fa-coffee]
- [Cutlery, cutlery, data-icon: fa-cutlery]
- [Table, table, data-icon: fa-table]
- [Magic, magic, data-icon: fa-magic]
- [Truck, truck, data-icon: fa-truck]
- [Pencil, pencil, data-icon: fa-pencil]
- [Cloud, cloud, data-icon: fa-cloud]
- [Scissors, scissors, data-icon: fa-scissors]
